### PR TITLE
Fixes scrolling

### PR DESCRIPTION
**Pull request by nigelhorne**
Scrolling a page would put the map in front of a CSS fixed element.  This code makes that behaviour optional.

### CODE REVIEW

**Comment by nigelhorne** [comment]
In hindsight the space between %s %s wasn't needed, it can be:

```
    my $map = sprintf(
        '<div id="%s" style="width: %s; height: %s%s"></div>',
        @{$self}{qw/ id width height / },
        exists($self->{'z_axis'})
            ? '; z-axis: ' . $self->{'z_axis'} : ''
    );
```

**Comment by leejo** [comment]
Squashed and merged, thanks! Will push out an update to CPAN shortly.

**Comment by nigelhorne** [comment]
Sweet.  Thank you.

**Comment by leejo** [comment]
Thank you for the contributions 😃  - i've added you to the list of contributors: https://github.com/Humanstate/html-googlemaps-v3/commit/e6245ceee1c2ee97e1c41d91cd622f74e283b35b#diff-ec59dd84d8ad51d62a8ea9abffc4755bR408

**Pull request merged**
